"""initial schema

Revision ID: 7be5beac88bb
Revises: 
Create Date: 2026-09-05 15:04:19.165794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be5beac88bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('garment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garment_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('where_text', sa.String(length=255), nullable=False),
    sa.Column('measure_rule', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garment_type_id'], ['garment_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garment_type_id', 'name')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('instagram', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('garment_type_id', sa.Integer(), nullable=False),
    sa.Column('numbers_kind', sa.String(length=16), nullable=False),
    sa.Column('link_code', sa.String(length=32), nullable=False),
    sa.Column('shop_url', sa.String(length=512), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garment_type_id'], ['garment_types.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_link_code'), 'products', ['link_code'], unique=True)
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name')
    )
    op.create_table('measure_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=64), nullable=True),
    sa.Column('recommended_size_id', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('photo_delete_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_code', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recommended_size_id'], ['product_sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measure_requests_view_code'), 'measure_requests', ['view_code'], unique=True)
    op.create_table('size_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_size_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('value_cm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['measurement_criteria.id'], ),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_sizes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_size_id', 'criterion_id')
    )
    op.create_table('extracted_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('value_cm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['measurement_criteria.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['measure_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_measurements')
    op.drop_table('size_measurements')
    op.drop_index(op.f('ix_measure_requests_view_code'), table_name='measure_requests')
    op.drop_table('measure_requests')
    op.drop_table('product_sizes')
    op.drop_index(op.f('ix_products_link_code'), table_name='products')
    op.drop_table('products')
    op.drop_table('shops')
    op.drop_table('measurement_criteria')
    op.drop_table('jobs')
    op.drop_table('garment_types')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
